# -*- coding: utf-8 -*-
"""Vetores - Exercicio_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mhB87e2sX7-tgiM2zgVGXIxdOY_Y_li7
"""

# Softex - Recife
# Janderson Freitas
# Array - Question 2

# Variáveis:
# Note que 'array' é vazio e len(array) é igual a zero.
array = []                   
sum = 0                      

for i in range(5):
  while True:   # Estrutura de repetição só será finalizada com o comando 'break'.
  # Abaixo estrutura para tratamento de erros de entrada
    try:   
      array.append(float(input('Enter a Number: ')))
      sum = sum + array[i]       
      break     
    except ValueError:   
      print("Enter Error!")   
      print("Please, Enter a valid Value!")  

# Imprimindo os elementos do vetor e a soma total deles. 
print(f'Equal vector sum is {sum}')
for i in range(5):                 
  print(array[i])