# -*- coding: utf-8 -*-
"""Vetores - Exercicio_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JqXNDJXmTqWNmERt1NcM_5286F9DVO1N
"""

# Softex - Recife
# Janderson Freitas
# Array - Question 3

# Variáveis:
vector = []
vector_5x = []

for i in range(10):
  while True:
    try:
      vector.append(float(input("Enter a number for Vector: ")))
      vector_5x.append(vector[i]*5)
      break
    except ValueError:
      print("Error!")
      print("Please, Enter a valid Value!")   

print("")
print("Vetor  vector*5")
for i in range(10):
  print(f"{vector[i]}      {vector_5x[i]}")