# -*- coding: utf-8 -*-
"""Vetores - Exercicio_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sdG8jhQEiYvy0xGSFbkQC50mJam0t3Cm
"""

# Softex - Recife
# Janderson Freitas
# Array - Question 2


name_array = []

for i in range(0,5):
  while True:
    try:
      name_array.append(input(f"digite o nome {i+1}:"))
      break
    except ValueError:
      print("Error!")
      print("Please, Enter a valid Value!")  

print(name_array)
print("") #
for i in range(0,5):
  print(name_array[i])

print("")
for i in range(5,0,-1):
  print(name_array[i-1])

names = [] #Declara lista vazia, conjunto unitário vazio

for i in range(5):
  while True:
    try:
      name = input(f"digite o nome {i+1}:")
      names.append(name)
      break
    except ValueErro:
      print("Error!")
      print("Please, Enter a valid Value!")


print(names)
print(sorted(names, reverse = True))

