# -*- coding: utf-8 -*-
"""Insertion_Sort.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IanW77e5arroRS-vmiNIbbADsK7JT4ez
"""

#Softex - Recife
#Janderson Freitas
# Insertion Sort


# Declarando Função para Insertion Sort
def insertion_Sort(array):
	for i in range(1, len(array)):
		key = array[i]

		#Move elementos do vetor que são maiores que key, 
		#para uma posição à frente de sua posição atual.
		j = i-1
		while j >=0 and key < array[j] :
				array[j+1] = array[j]
				j -= 1
		array[j+1] = key


# Criação do Vetor de teste
array = [21, 11, 47, 105, 33, 17, 9, 1, 61, 55]

insertion_Sort(array)

print ("A ordem crescente do Vetor é:")
for i in range(len(array)):
	print (f"{array[i]}")